apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      port: 80         # Port inside the cluster
      nodePort: 30007
  selector:
    app: nginx    
  type: nodePort 